version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.31.0
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mongo
            uri: >-
              mongodb+srv://admin:Harleypoisoncat-256@developmentcluster-8hgxr.mongodb.net/admin?retryWrites=true
            database: project_one_dev